---
title: "ESM 204 HW 4"
author: "Peter Omasta, Jennifer Truong, and Veronica Weber"
date: "5/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

# Attach packages
library(tidyverse)
library(janitor)
```

```{r Functions}

# Maybe all of these can become one function later

# Function for finding temperature under BAU ----

# tau(t) = min(Tt/100, T)
bau_temp = function(t, T){
  tau = min((T*t)/100, T)
  return(tau)
}

# Function for fraction of economic activity that is retained ----

# "consumption" = economic activity)

# K(t) = exp(−beta*tau(t)^2)
econ_activity_retained = function(t, beta, tau){
  k_t = exp(-beta*tau)
  return(k_t)
}

# Function for total consumption at time t ----

# C(t) = K(t)exp(gt)
consumption = function(t, k_t, g){
  c_t = k_t*exp(g*t)
  return(c_t)
}


# Function for society's utility ---

# U(C) = (C1−eta)/(1 − eta)
society_utility = function(c_t, eta){
  u_c = (c_t^(1-eta))/(1-eta)
  return(u_c)
}


# Function for discount rate ----

# Discount rate - Ramsey rule
discount_rate = function(delta, eta, g){
  r = delta + eta*g
  return(r)
  }
```

```{r Parameters}

# Setting up vector for time t
year = c(0:200)

# Use the following base case parameters for this model: delta = .005, eta = .5, g = .01, beta = .05.

```

# 1. Plots 

### a) temperature over time

- no climate change (T = 0)
- moderate climate change (T = 2)
- extreme climate change (T = 8)

```{r Finding temperature over time}

# Find BAU temp under T = 0
temp_t_0 = lapply(year, bau_temp, T = 0)

# Find BAU temp under T = 2
temp_t_2 = lapply(year, bau_temp, T = 2)

# Find BAU temp under T = 8
temp_t_8 = lapply(year, bau_temp, T = 8)

# Create data frame
temperature_df = tibble(year, temp_t_0, temp_t_2, temp_t_8) %>% 
  rename("no_cc" = "temp_t_0",
         "moderate_cc" = "temp_t_2",
         "extreme_cc" = "temp_t_8")
```

```{r Plot of temperature vs time}

# Code doesn't work for now - need to figure out what's wrong

ggplot() +
  geom_point(temperature_df,
             aes(x = year, y = no_cc),
             color = "green") +
  geom_point(temperature_df,
             aes(x = year, y = moderate_cc),
             color = "yellow") +
  geom_point(temperature_df,
             aes(x = year, y = extreme_cc),
             color = "red")
```

### b) Consumption over time

- no climate change (T = 0)
- moderate climate change (T = 2)
- extreme climate change (T = 8)

```{r Finding consumption over time}

# Find consumption under T = 0
consumption_t_0 = lapply(year, econ_activity_retained, beta = .05, tau = temp_t_0)

# Find consumption under T = 2
temp_t_2 = lapply(year, bau_temp, T = 2)

# Find consumption under T = 8
temp_t_8 = lapply(year, bau_temp, T = 8)

# Create data frame
temperature_df = tibble(year, temp_t_0, temp_t_2, temp_t_8) %>% 
  rename("no_cc" = "temp_t_0",
         "moderate_cc" = "temp_t_2",
         "extreme_cc" = "temp_t_8")

```

### c) Undiscounted utility over time
